# Generated by Django 5.2.17 on 2026-09-11 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('static', 'Statique (contenu dans le QR)'), ('dynamic', 'Dynamique (redirigeable)')], db_index=True, default='static', max_length=16)),
                ('slug', models.CharField(blank=True, editable=False, max_length=32, unique=True, verbose_name='lien court')),
                ('type_id', models.CharField(default='url', max_length=24, verbose_name='type')),
                ('label', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.TextField(blank=True, verbose_name='contenu encodé')),
                ('target_url', models.URLField(blank=True, max_length=2048, verbose_name='URL de destination')),
                ('design', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('redirect_mode', models.CharField(choices=[('302', '302 — temporaire (compté, non mis en cache)'), ('301', '301 — permanent (les navigateurs se souviennent, on perd le comptage)'), ('307', '307 — reteste la méthode')], default='302', max_length=4)),
                ('utm_mode', models.BooleanField(default=False, verbose_name='ajouter les UTM')),
                ('scan_count_total', models.BigIntegerField(default=0, verbose_name='scans (cumul)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'QR code',
                'verbose_name_plural': 'QR codes',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='QrReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_ip_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('reviewing', 'En cours'), ('dismissed', 'Écarté'), ('frozen', 'Gel')], default='new', max_length=16)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='qr.qrcode')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QrVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('change', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='qr.qrcode')),
            ],
            options={
                'verbose_name': 'modification',
                'verbose_name_plural': 'historique des modifications',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['owner', 'deleted_at', '-created_at'], name='qr_owner_list_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['kind', 'is_active'], name='qr_kind_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='qrcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'dynamic'), _negated=True), ('target_url__gt', ''), _connector='OR'), name='qr_dynamic_requires_target'),
        ),
        migrations.AddConstraint(
            model_name='qrcode',
            constraint=models.CheckConstraint(condition=models.Q(('scan_count_total__gte', 0)), name='qr_scan_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='qrreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'new')), fields=('qr', 'reporter_ip_hash'), name='report_once_per_ip'),
        ),
        migrations.AddIndex(
            model_name='qrversion',
            index=models.Index(fields=['qr', '-created_at'], name='qrver_qr_recent_idx'),
        ),
    ]
