# Generated by Django 5.2.17 on 2026-09-15 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ('-created_at', '-id'), 'permissions': [('creer_sans_facturation', "Peut creer des QR depuis l'espace admin sans facturation")], 'verbose_name': 'QR code', 'verbose_name_plural': 'QR codes'},
        ),
        migrations.AddField(
            model_name='qrcode',
            name='origine',
            field=models.CharField(choices=[('client', 'Créé par le client'), ('admin', "Créé depuis l'espace admin"), ('import', 'Importé en masse')], db_index=True, default='client', max_length=16),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['origine', '-created_at'], name='qr_origine_recent_idx'),
        ),
    ]
