# Generated by Django 5.2.17 on 2026-09-16 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_origine_et_permission_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Normalisé : majuscules, sans espace.', max_length=48, verbose_name='code')),
                ('libelle', models.CharField(blank=True, max_length=160, verbose_name='intitulé affiché')),
                ('remise_type', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant', 'Montant'), ('livraison', 'Livraison offerte'), ('acces', 'Accès offert')], default='pourcentage', max_length=12)),
                ('remise_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valeur de la remise')),
                ('devise', models.CharField(blank=True, default='EUR', max_length=3, verbose_name='devise')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('usages_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='usages maximum')),
                ('usages', models.PositiveIntegerField(default=0, verbose_name='usages constatés')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_promo', to=settings.AUTH_USER_MODEL, verbose_name='compte')),
                ('qr', models.ForeignKey(blank=True, help_text="L'offre peut exister sans QR (code imprimé à la main) ; avec, la vérification se fait au scan.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_promo', to='qr.qrcode', verbose_name='QR associé')),
            ],
            options={
                'verbose_name': 'code promo',
                'verbose_name_plural': 'codes promo',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['owner', '-created_at'], name='qr_promo_owner_recent'), models.Index(fields=['owner', 'expire_le'], name='qr_promo_owner_expire'), models.Index(fields=['qr', 'actif'], name='qr_promo_qr_actif')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'code'), name='qr_promo_code_unique_par_compte')],
            },
        ),
    ]
