# Generated by Django 5.2.17 on 2026-09-15 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_grille_tarifaire_reelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='abonnement', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.CharField(choices=[('none', 'Aucun (manuel)'), ('stripe', 'Stripe'), ('mobile_money', 'Paiement mobile')], default='none', max_length=16)),
                ('statut', models.CharField(choices=[('trialing', "Période d'essai"), ('active', 'Actif'), ('past_due', 'Paiement en retard'), ('paused', 'En pause'), ('canceled', 'Annulé'), ('incomplete', 'Paiement initial non abouti')], db_index=True, default='incomplete', max_length=24)),
                ('palier', models.CharField(default='free', help_text='Ce qui est payé — `User.plan`.', max_length=16)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('abonnement_fournisseur_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('prix_id', models.CharField(blank=True, max_length=128)),
                ('debut', models.DateTimeField(blank=True, null=True)),
                ('periode_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('en_sursis_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-maj_le'],
            },
        ),
        migrations.CreateModel(
            name='EvenementPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=128, unique=True)),
                ('fournisseur', models.CharField(choices=[('none', 'Aucun (manuel)'), ('stripe', 'Stripe'), ('mobile_money', 'Paiement mobile')], default='stripe', max_length=16)),
                ('type_evenement', models.CharField(db_index=True, max_length=64)),
                ('recu_le', models.DateTimeField(auto_now_add=True)),
                ('charge', models.JSONField(default=dict)),
                ('traite', models.BooleanField(default=False)),
                ('erreur', models.TextField(blank=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='billing.abonnement')),
            ],
            options={
                'verbose_name': 'événement de paiement',
                'verbose_name_plural': 'événements de paiement',
                'ordering': ['-recu_le'],
            },
        ),
        migrations.CreateModel(
            name='PaiementMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('palier', models.CharField(max_length=16)),
                ('montant_centimes', models.PositiveIntegerField()),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('fournisseur', models.CharField(blank=True, max_length=32)),
                ('statut', models.CharField(choices=[('pending', "En attente d'approbation"), ('confirmed', 'Confirmé'), ('expired', 'Expiré'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=16)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField(db_index=True)),
                ('confirme_le', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_mobiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paiement mobile',
                'verbose_name_plural': 'paiements mobiles',
                'ordering': ['-cree_le'],
            },
        ),
    ]
