import fs from 'node:fs'; import vm from 'node:vm'; import sharp from 'sharp'; import path from 'node:path';
const lib = fs.readFileSync('/home/user/.probe/qrcode.min.js','utf8');
let orig = fs.readFileSync('/home/user/orig/orig.js','utf8') + '\n;globalThis.__api={state,generate};\n';
let lastSvg='';
const mkNode=id=>({id,style:{},dataset:{},_h:'',set innerHTML(v){this._h=v},get innerHTML(){return this._h},set src(v){lastSvg=v},removeAttribute(){lastSvg=''},addEventListener(){},textContent:'',querySelectorAll:()=>[],click(){},files:[]});
const nodes={}; const doc={getElementById:id=>(nodes[id]??=mkNode(id)),querySelectorAll:()=>[],documentElement:mkNode('h'),createElement:()=>mkNode('c'),addEventListener(){}};
const ctx=vm.createContext({document:doc,console,btoa:s=>Buffer.from(s,'binary').toString('base64'),unescape:s=>decodeURIComponent(escape(s)),encodeURIComponent,decodeURIComponent,Image:class{},FileReader:class{}});
vm.runInContext('var window=globalThis;'+lib,ctx);
vm.runInContext('var qrcode=window.qrcode;\n'+orig,ctx);
const api=vm.runInContext('globalThis.__api',ctx);
api.state.type='text'; api.state.data={txt:'HELLO'}; api.state.margin=40; api.generate();
fs.writeFileSync('/tmp/hello-app.svg', api.state.svg);
console.log('svg size attr:', api.state.svg.match(/width="(\d+)"/)[1]);
const png = await sharp(Buffer.from(api.state.svg),{density:120}).flatten({background:'#fff'}).png().toBuffer();
fs.writeFileSync('/tmp/hello-app.png', png);
console.log('written', png.length, 'bytes');
