# Generated by Django 5.2.17 on 2026-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='horodatage')),
                ('qr_id', models.BigIntegerField(verbose_name='QR')),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
                ('day', models.DateField(verbose_name='jour')),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(blank=True, max_length=96, null=True)),
                ('ip_trunc', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_prefix_len', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('referer_domain', models.CharField(blank=True, max_length=190, null=True)),
                ('device_class', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Ordinateur'), ('tablet', 'Tablette'), ('bot', 'Robot'), ('unknown', 'Inconnu')], default='unknown', max_length=12)),
                ('is_bot', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(default=302)),
                ('scan_id', models.CharField(max_length=32)),
                ('source', models.CharField(choices=[('stream', 'File de scan'), ('access_log', 'Journal Caddy'), ('manual', 'Correction manuelle')], default='stream', max_length=16)),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
                'db_table': 'analytics_scanevent',
                'managed': False,
                'default_related_name': 'scanevents',
            },
        ),
        migrations.CreateModel(
            name='QrDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.BigIntegerField(db_index=True, verbose_name='QR')),
                ('day', models.DateField(db_index=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('scans', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0, help_text='Approximation HyperLogLog.')),
                ('mobile', models.PositiveIntegerField(default=0)),
                ('desktop', models.PositiveIntegerField(default=0)),
                ('tablet', models.PositiveIntegerField(default=0)),
                ('bot_blocked', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'statistique quotidienne',
                'verbose_name_plural': 'statistiques quotidiennes',
                'db_table': 'analytics_qrdailystats',
                'indexes': [models.Index(fields=['qr_id', '-day', 'country_code'], name='qrdaily_read_idx')],
                'constraints': [models.UniqueConstraint(fields=('qr_id', 'day', 'country_code'), name='qrdaily_qr_day_country_uniq')],
            },
        ),
    ]
