# Generated by Django 5.2.17 on 2026-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_scanevent_raw_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, unique=True, verbose_name='jour')),
                ('scans', models.BigIntegerField(default=0)),
                ('visiteurs_uniques', models.BigIntegerField(default=0)),
                ('mobile', models.BigIntegerField(default=0)),
                ('desktop', models.BigIntegerField(default=0)),
                ('tablette', models.BigIntegerField(default=0)),
                ('bots_bloques', models.BigIntegerField(default=0)),
                ('qr_uses_statiques', models.BigIntegerField(default=0)),
                ('qr_uses_dynamiques', models.BigIntegerField(default=0)),
                ('qr_uses_admin', models.BigIntegerField(default=0)),
                ('qr_actifs', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'statistique quotidienne plateforme',
                'verbose_name_plural': 'statistiques quotidiennes plateforme',
                'db_table': 'analytics_platformdailystats',
                'ordering': ('-day',),
                'permissions': [('voir_analytique_plateforme', "Peut consulter l'analytique globale des scans")],
            },
        ),
    ]
