import { spawn } from 'node:child_process';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import puppeteer from 'puppeteer';
import sharp from 'sharp';
import { readBarcodesFromImageData, prepareZXingModule } from 'zxing-wasm/reader';
const PORT=4322, BASE=`http://127.0.0.1:${PORT}/`;
const server = spawn('node', ['node_modules/vite/bin/vite.js','preview','--port',String(PORT),'--strictPort'], {stdio:'ignore'});
const wait=async()=>{for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,200)); const ok=await new Promise(res=>{const q=http.get(BASE,r=>{r.resume();res(r.statusCode===200)});q.on('error',()=>res(false))}); if(ok)return;} throw 0;};
await wait();
await prepareZXingModule({overrideURL:path.resolve('node_modules/zxing-wasm/reader/zxing_reader.wasm'), fallback:()=>fetch('file://'+path.resolve('node_modules/zxing-wasm/reader/zxing_reader.wasm')).then(r=>r.arrayBuffer())});
const b = await puppeteer.launch({args:['--no-sandbox','--disable-dev-shm-usage']});
const p = await b.newPage();
await p.goto(BASE,{waitUntil:'networkidle0'});
await p.evaluate(()=>{const el=document.querySelector('#url-url');const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(el,'https://exemple.com/tarifs-2026?src=qr');el.dispatchEvent(new Event('input',{bubbles:true}));});
await new Promise(r=>setTimeout(r,600));
const geo = await p.$eval('.qrc-preview-svg svg', el=>{const r=el.getBoundingClientRect(); return {w:r.width,h:r.height,attrs:{viewBox:el.getAttribute('viewBox'),width:el.getAttribute('width'),height:el.getAttribute('height')}, kids:el.children.length};});
console.log('svg geometry:', JSON.stringify(geo));
const html = await p.$eval('.qrc-preview-svg svg', el=>el.outerHTML);
fs.writeFileSync('/tmp/live.svg', html);
async function dec(buf,label,density){const {data,info}=await sharp(buf, density?{density}:undefined).flatten({background:'#fff'}).raw().ensureAlpha().toBuffer({resolveWithObject:true}); const r=await readBarcodesFromImageData({data:new Uint8ClampedArray(data),width:info.width,height:info.height},{tryHarder:true}); console.log(label,'->',r.length?JSON.stringify(r[0].text):'NULL',`(${info.width}px)`);}
await dec(Buffer.from(html), 'svg outerHTML raw  :');
await dec(Buffer.from(html), 'svg outerHTML @400  :', 400);
const box = await p.$eval('.qrc-preview-svg svg', el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};});
const shot = await p.screenshot({clip:{x:Math.floor(box.x),y:Math.floor(box.y),width:Math.ceil(box.w),height:Math.ceil(box.h)}});
fs.writeFileSync('/tmp/live-shot.png', shot);
await dec(shot, 'screenshot @1x        :');
await p.setViewport({width:1280,height:900,deviceScaleFactor:3});
await new Promise(r=>setTimeout(r,300));
const box2 = await p.$eval('.qrc-preview-svg svg', el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};});
const shot2 = await p.screenshot({clip:{x:Math.floor(box2.x),y:Math.floor(box2.y),width:Math.ceil(box2.w),height:Math.ceil(box2.h)}, captureBeyondViewport:true});
await dec(shot2, 'screenshot @3x        :');
await b.close(); server.kill('SIGTERM');
