# Generated by Django 5.2.17 on 2026-09-11 11:04

import apps.accounts.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('username', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='e-mail vérifié')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='suspendu')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='motif de suspension')),
                ('locale', models.CharField(default='fr', max_length=10)),
                ('timezone_name', models.CharField(default='Europe/Paris', max_length=64, verbose_name='fuseau')),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro'), ('team', 'Équipe')], default='free', max_length=16)),
                ('plan_until', models.DateTimeField(blank=True, null=True, verbose_name="plan valable jusqu'au")),
                ('consent_tracking_at', models.DateTimeField(blank=True, null=True, verbose_name='consentement mesure, à')),
                ('consent_ip_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('marketing_opt_in', models.BooleanField(default=False, verbose_name='emails marketing')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'compte',
                'verbose_name_plural': 'comptes',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code de vérification',
                'verbose_name_plural': 'codes de vérification',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_em_user_id_2e8c23_idx')],
            },
        ),
    ]
